import Head from "next/head";

//Import icons
import { BsFillMoonStarsFill, BsGithub, BsLinkedin } from "react-icons/bs";
import { AiFillGitlab, AiFillHtml5 } from "react-icons/ai";
import { DiJqueryLogo, DiPython, DiReact, DiGit, DiCss3 } from "react-icons/di";
import {
  SiMysql,
  SiMongodb,
  SiExpress,
  SiNodedotjs,
  SiBootstrap,
  SiTailwindcss,
} from "react-icons/si";
import { TbBrandJavascript, TbBrandNextjs } from "react-icons/tb";

//Import images
import Image from "next/image";
import devIcon from "../public/programmer.png";
import portfolio from "../public/web-portfolio-p1-sc.PNG";
import slytheryn from "../public/slytheryn-p2.PNG";

export default function Home() {
  return (
    <div>
      <Head>
        <title>JefferScript | Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 font-mono">
        <section className="h-screen">
          <nav className="py-7 mb-8 flex justify-between">
            <h1 className="text-xl font-burtons">JefferScript</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-8">
            <h2 className="text-4xl font-bold text-teal-600  ">
              Jefferson Rosimo
            </h2>
            <h3 className="text-2xl py-2">Software Developer</h3>
            <p className="text-md py-5 leading-6 text-gray-800">
              An electronics engineer who recently graduated from a web
              development bootcamp as a scholar of Department of Information and
              Communications Technology. Looking for a frontend or backend
              developer job.
            </p>
          </div>
          <div className="text-4xl flex justify-center gap-16 py-3 text-gray-700">
            <BsGithub />
            <BsLinkedin />
            <AiFillGitlab />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-600 rounded-full  h-60 w-60 mt-8 overflow-hidden">
            <Image src={devIcon} alt="developer image" fill />
          </div>
        </section>

        <section className="mt-32">
          <div className="text-gray-800">
            <h3 className="text-xl">Tech Stack</h3>
            <div className="text-md py-5 leading-6 text-gray-800">
              <div className="shadow-lg rounded-xl p-5">
                <h4 className="text-lg">Basic</h4>
                <ul className="flex justify-center flex-wrap text-center">
                  <li className="px-6 py-2  flex flex-col items-center">
                    <SiTailwindcss className="text-4xl" /> Tailwindcss
                  </li>
                  <li className="px-8 py-2  flex flex-col items-center">
                    <TbBrandNextjs className="text-4xl" /> NextJs
                  </li>
                  <li className="px-8 py-2  flex flex-col items-center">
                    <DiJqueryLogo className="text-4xl" /> jQuery
                  </li>
                  <li className="px-8 py-2  flex flex-col items-center">
                    {" "}
                    <SiMysql className="text-4xl" /> MySQL
                  </li>
                  <li className="px-8 py-2  flex flex-col items-center">
                    <DiPython className="text-4xl" /> Python
                  </li>
                </ul>
              </div>
              <div className="mt-4 shadow-lg rounded-xl p-5">
                <h4 className="text-lg">Intermediate</h4>
                <ul className="flex justify-center flex-wrap text-center">
                  <li className="px-6 py-2  flex flex-col items-center">
                    <TbBrandJavascript className="text-4xl" /> JavaScript
                  </li>
                  <li className="px-6 py-2  flex flex-col items-center">
                    <SiMongodb className="text-4xl" /> MongoDb
                  </li>
                  <li className="px-6 py-2  flex flex-col items-center">
                    {" "}
                    <SiExpress className="text-4xl" /> ExpressJs
                  </li>
                  <li className="px-6 py-2  flex flex-col items-center">
                    <DiReact className="text-4xl" /> ReactJs
                  </li>
                  <li className="px-6 py-2  flex flex-col items-center">
                    <SiNodedotjs className="text-4xl" /> NodeJs
                  </li>
                  <li className="px-6 py-2  flex flex-col items-center">
                    <DiGit className="text-4xl" /> Git
                  </li>
                  <li className="px-6 py-2  flex flex-col items-center">
                    <SiBootstrap className="text-4xl" /> Bootstrap
                  </li>
                </ul>
              </div>
              <div className="mt-4 shadow-lg rounded-xl p-5">
                <h4 className="text-lg">Advanced</h4>
                <ul className="flex justify-center flex-wrap text-center">
                  <li className="px-8 py-2  flex flex-col items-center">
                    <AiFillHtml5 className="text-4xl" /> HTML
                  </li>
                  <li className="px-8 py-2  flex flex-col items-center">
                    <DiCss3 className="text-4xl" /> CSS
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-xl">Projects</h3>
            <div>
              <div className="shadow-md p-3 border text-center mt-5">
                <p>
                  Web Portfolio | HTML, CSS, Bootstrap and Vanilla Javascript
                </p>
                <a href="https://jefferscript-portfolio.vercel.app/">
                  <Image src={portfolio} alt="web portfolio project" />
                </a>
                <div>
                  <a href="https://jefferscript-portfolio.vercel.app/">Live</a>
                  <a className="ml-4" href="">
                    Code
                  </a>
                </div>
              </div>
              <div className="shadow-md p-3 border text-center mt-5">
                <p>Snake game | HTML, CSS and Vanilla Javascript</p>
                <a href="">
                  <Image src={slytheryn} alt="slytheryn snake game" />
                </a>
                <div>
                  <a href="">Live</a>
                  <a className="ml-4" href="">
                    Code
                  </a>
                </div>
              </div>
              <div className="shadow-md p-3 border text-center mt-5">
                <p>
                  Web Portfolio | HTML, CSS, Bootstrap and Vanilla Javascript
                </p>
                <a href="">
                  <Image src={portfolio} alt="web portfolio project" />
                </a>
                <div>
                  <a href="">Live</a>
                  <a className="ml-4" href="">
                    Code
                  </a>
                </div>
              </div>
              <div className="shadow-md p-3 border text-center mt-5">
                <p>
                  Web Portfolio | HTML, CSS, Bootstrap and Vanilla Javascript
                </p>
                <a href="">
                  <Image src={portfolio} alt="web portfolio project" />
                </a>
                <div>
                  <a href="">Live</a>
                  <a className="ml-4" href="">
                    Code
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      {/* <footer>
        <a
          className="text-xs"
          href="https://www.flaticon.com/free-icons/programmer"
          title="programmer icons"
          target="_blank"
          rel="noreferrer"
        >
          Programmer icons created by kerismaker - Flaticon
        </a>
      </footer> */}
    </div>
  );
}
